name: integracion continua con java

on:
  pull_request:
    branches: [ master ]
    jobs:
      ciToMaster:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v1

            with:
              java-version: 1.17
          - run: npm ci
          - run: npm test
          - run: npm run build
            
